name: Haciendo prueba en el codigo

on:
  push:
    branches:
      - HacerMejorasAqui

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'  # Asegúrate de usar la versión correcta de .NET Core

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      id: buildId
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      if: ${{github.event_name == 'push'}}
      run: echo "${{job.test}}, ${{steps.buildId.outputs}} "
